---
development:
  cloud_name: hum-tum-union
  api_key: '111853832223453'
  api_secret: y9aWeDcLe_1c8UuHvPf70JSMyDM
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: hum-tum-union
  api_key: '111853832223453'
  api_secret: y9aWeDcLe_1c8UuHvPf70JSMyDM
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: hum-tum-union
  api_key: '111853832223453'
  api_secret: y9aWeDcLe_1c8UuHvPf70JSMyDM
  enhance_image_tag: true
  static_image_support: false
